### PR TITLE
Frontend ci

### LINKED ISSUE #11: frontend CI
set up github actions for the frontend

### PR DESCRIPTION
**Pull request by IdreesSamadi**
build and lint CI set up for the frontend Closes #11

### CODE REVIEW

**Review by RuthgerD — CHANGES_REQUESTED** [review]
Should consider caching the node modules:
```yml
- uses: actions/cache@v2
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
```

Also I think we should limit the frontend ci to just test on linux, as long as we don't do anything platform specific at build time there's not really a use case for multi platform

**Comment by IdreesSamadi** [comment]
now only runs on Ubuntu and the npm packages are cached,

**Review by RuthgerD — APPROVED** [review]

**Review by SyncInProgress — APPROVED** [review]
Great job. I couldn't really find anything missing and it looks like all the steps are there.

**Review by AeroStun — APPROVED** [review]
LGTM; please squash when merging

**Pull request merged**
