### PR TITLE
Graph tests

### PR DESCRIPTION
**Pull request by IdreesSamadi**

### CODE REVIEW

**Comment by RuthgerD** [comment]
Is this intended to be merged?

**Comment by SyncInProgress** [comment]
Good basic design for the graph. An excellent starting point to work on the visualization of events.

**Review by RuthgerD — APPROVED** [review]
As we agreed to keep using the mock data file for now I don't have any problems with this :+1:

**Review by SyncInProgress — APPROVED** [review]

**Comment by sodero** [comment]
A general comment, not sure whether it's applicable to this PR: For PR:s changing the looks of the front-end, an attachment showing the result would be great.

**Pull request merged**
