### PR TITLE
BUGFIX-US12: Incorrect Scrolling distance calculations

### PR DESCRIPTION
**Pull request by Asiya-Ismail**
# BUGFIX-US12: Incorrect Scrolling distance calculations

## Description:

- Auto-scrolling was calculating incorrectly the scrolling distance when user uses the left and right arrow keys. It was not taking the distance the graph makes during arrow key usage into account when calculating scrolling distance.

## Testing:

- Testing was done using the current event generator.

### CODE REVIEW

**Comment by RuthgerD** [comment]
16 commits, title: "BUGFIX-US12", i am not going to read the description until there is a proper title and there is a single commit to look at.

**Comment by Asiya-Ismail** [comment]
I will work on rebasing now

**Comment by Asiya-Ismail** [comment]
Tried rebasing didn't seem to give the desired outcome. Any suggestions how to show only commits related to this PR ? Also I noticed these extra commits don't seem to show up in the PR I made in forked repo but only in the PR made upstream, do you maybe know why that is?

**Comment by ktpa** [comment]
> Tried rebasing didn't seem to give the desired outcome. Any suggestions how to show only commits related to this PR ? Also I noticed these extra commits don't seem to show up in the PR I made in forked repo but only in the PR made upstream, do you maybe know why that is?

It is because we have not PR'd the new changes changes to this repository yet. They are local to our fork. I would advice closing this one and start with the PR on our fork first.

**Pull request closed without merging**
