### PR TITLE
Keybind and shortcut panel

### PR DESCRIPTION
**Pull request by ktpa**
Small summary:

Keybinds are working and separated for the upcoming multi-graph feature.

Shortcuts has been implemented as another section of the settings.

### CODE REVIEW

**Comment by RuthgerD** [comment]
I have no idea what was added due to reformatting... will test it on my machine later and see if it works properly

**Comment by ktpa** [comment]
> I have no idea what was added due to reformatting... will test it on my machine later and see if it works properly

This is an issue, yes. Would you like me to add the .prettierrc to this PR? It will make the frontend so much easier to have a look at.

**Comment by RuthgerD** [comment]
If you can do that it would be great

**Comment by ktpa** [comment]
> If you can do that it would be great

It has been done.

**Comment by RuthgerD** [comment]
I am a big lazy and didnt check this very well, do you swear uppon everything that is holy that this PR is correct and does what we want? (then ill merge it)

**Comment by ktpa** [comment]
> I am a big lazy and didnt check this very well, do you swear uppon everything that is holy that this PR is correct and does what we want? (then ill merge it)

I swear upon everything that is holy that this PR is correct.

**Review by RuthgerD — APPROVED** [review]

**Comment by RuthgerD** [comment]
Thanks!

**Pull request merged**
