### PR TITLE
Backend: use of partial keywords (wildcard) when filtering

### PR DESCRIPTION
**Pull request by alrapal**
# "Wildcard" / partial keyword filtering

originally ItJustWorksBetterTM/EiffelVis#43

## Description:
* Allows the user to filter (Type, SourceHost and SourceName) without having to enter the exact name.
* This is done using a combination of String::contains and String::To_lowercase. 
* The input and event attribute are both converted to lowercase in order allow for more flexibility when filtering.
* Avoided using regex due to the simple nature of these queries where string operations outperforms regex.

## Testing environment:
* Graph size of 4096 (4 times the default).
* Waited until the number of events reached the capacity of the graph.
* Had the generator running with the datadump while applying filters.
* Locally run

## Testing results:
* No visual performance decrease when applying filters.
* Filter results returned in an acceptable timeframe.
* No issues interacting with the graph when applying filters.

### CODE REVIEW

**Comment by RuthgerD** [comment]
We discussed a bit and came to the conclusion that we don't want this to be always on, and that this needs to be generalized into its own concept (inside the code) so that we can have more search modes in the future.
I dont have any great tips this friday evening but ill try to think up something actionable.

**Comment by alrapal** [comment]
> We discussed a bit and came to the conclusion that we don't want this to be always on, and that this needs to be generalized into its own concept (inside the code) so that we can have more search modes in the future. I dont have any great tips this friday evening but ill try to think up something actionable.

Could we include some tickbox in the front-end to include so we activate or de-activate the wildcard filtering? 
We could then have several sub-classes based on the different type of filtering if you have any other search would appear in the future? 

We can also discuss this a bit more on Friday =)

**Comment by RuthgerD** [comment]
> > We discussed a bit and came to the conclusion that we don't want this to be always on, and that this needs to be generalized into its own concept (inside the code) so that we can have more search modes in the future. I dont have any great tips this friday evening but ill try to think up something actionable.
> 
> Could we include some tickbox in the front-end to include so we activate or de-activate the wildcard filtering? We could then have several sub-classes based on the different type of filtering if you have any other search would appear in the future?
> 
> We can also discuss this a bit more on Friday =)

I dont really care what the frontend does, but I want the backend to handle what you describe elegantly.

the `EventFilter` enum now contains `String` (in various ways) that is filtered on and that needs to be changed to an enum instead to support multiple ways of filtering.

I think this is quite simple now I think about it, ill prototype something later today (if I have time)

**Comment by alrapal** [comment]
> I think this is quite simple now I think about it, ill prototype something later today (if I have time)

ok, let us know when you have something concrete and we can go from there! :D

**Comment by RuthgerD** [comment]
alternative has been merged, thanks for bringing this up as idea!

**Pull request closed without merging**
